[versions]
agp = "8.13.1"
kotlin = "2.2.20"

kotlinx-io = "0.8.2"

kotlinpoet = "2.2.0"

selfie = "2.5.4"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-xml = { module = "io.github.pdvrieze.xmlutil:serialization", version = "0.91.2" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
square-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

diffplug-selfie = { module = "com.diffplug.selfie:selfie-runner-junit5", version.ref = "selfie" }

android-libraryGradlePlugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "agp" }
kotlin-multiplatformGradlePlugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.kotlin.multiplatform.library" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
